# Generated by Django 4.2.20 on 2025-04-21 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='checked_out_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_cds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cd',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cd',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('checked_out', 'Checked Out'), ('reserved', 'Reserved')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='CDRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('requested_days', models.IntegerField(default=14)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.cd')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cd_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
