# Generated by Django 4.2.20 on 2025-04-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cd_checked_out_to_cd_due_date_cd_status_cdrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
