# Generated by Django 4.2.20 on 2025-04-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_collection_allowed_users_collectionaccessrequest'),
        ('users', '0003_profile_birthday'),
    ]

    operations = [
    ]
