# Generated by Django 4.2.20 on 2025-04-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_collection_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
