# Generated by Django 4.2.20 on 2025-04-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
